---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm-secret
  namespace: student-if220129
type: Opaque
data:
  realm.json: ewogICJyZWFsbSI6ICJhdXRvbWluZC1yZWFsbSIsCiAgImVuYWJsZWQiOiB0cnVlLAoKICAicm9sZXMiOiB7CiAgICAicmVhbG0iOiBbCiAgICAgIHsgIm5hbWUiOiAiVXNlciIgfSwKICAgICAgeyAibmFtZSI6ICJBZG1pbiIgfQogICAgXQogIH0sCgogICJjbGllbnRzIjogWwogICAgewogICAgICAiY2xpZW50SWQiOiAiYXV0b21pbmQtYmFja2VuZCIsCiAgICAgICJlbmFibGVkIjogdHJ1ZSwKICAgICAgInNlY3JldCI6ICJkcXFiNndEOGthTUxDSUtvSVlqbzJaQjZkUkpRb0liVSIsCiAgICAgICJwcm90b2NvbCI6ICJvcGVuaWQtY29ubmVjdCIsCiAgICAgICJwdWJsaWNDbGllbnQiOiB0cnVlLAogICAgICAic2VydmljZUFjY291bnRzRW5hYmxlZCI6IHRydWUsCiAgICAgICJkaXJlY3RBY2Nlc3NHcmFudHNFbmFibGVkIjogdHJ1ZSwKICAgICAgInJlZGlyZWN0VXJpcyI6IFsiaHR0cDovL2xvY2FsaG9zdDo1MTkxLyoiLCAiaHR0cHM6Ly9pZjIyMDEyOS5jbG91ZC5odGwtbGVvbmRpbmcuYWMuYXQvKiJdLAogICAgICAid2ViT3JpZ2lucyI6IFsiKiJdCiAgICB9LAogICAgewogICAgICAiY2xpZW50SWQiOiAiYXV0b21pbmQtZnJvbnRlbmQiLAogICAgICAiZW5hYmxlZCI6IHRydWUsCiAgICAgICJwcm90b2NvbCI6ICJvcGVuaWQtY29ubmVjdCIsCiAgICAgICJwdWJsaWNDbGllbnQiOiB0cnVlLAogICAgICAicmVkaXJlY3RVcmlzIjogWyJodHRwOi8vbG9jYWxob3N0OjQyMDAvKiJdLAogICAgICAid2ViT3JpZ2lucyI6IFsiaHR0cDovL2xvY2FsaG9zdDo0MjAwIl0KICAgIH0sCiAgICB7CiAgICAgICJjbGllbnRJZCI6ICJhdXRvbWluZC1zd2FnZ2VyIiwKICAgICAgImVuYWJsZWQiOiB0cnVlLAogICAgICAic2VjcmV0IjogImRxcWI2d0Q4a2FNTENJS29JWWpvMlpCNmRSSlFvSWJVIiwKICAgICAgInByb3RvY29sIjogIm9wZW5pZC1jb25uZWN0IiwKICAgICAgInB1YmxpY0NsaWVudCI6IHRydWUsCiAgICAgICJzdGFuZGFyZEZsb3dFbmFibGVkIjogdHJ1ZSwKICAgICAgImRpcmVjdEFjY2Vzc0dyYW50c0VuYWJsZWQiOiBmYWxzZSwKICAgICAgInJlZGlyZWN0VXJpcyI6IFsKICAgICAgICAgImh0dHBzOi8vaWYyMjAxMjkuY2xvdWQuaHRsLWxlb25kaW5nLmFjLmF0L3N3YWdnZXIvb2F1dGgyLXJlZGlyZWN0Lmh0bWwiLAogICAgICAgICAiaHR0cHM6Ly9pZjIyMDEyOS5jbG91ZC5odGwtbGVvbmRpbmcuYWMuYXQvYXBpL3N3YWdnZXIvb2F1dGgyLXJlZGlyZWN0Lmh0bWwiCiAgICAgIF0sCiAgICAgICJ3ZWJPcmlnaW5zIjogWwogICAgICAgICAiaHR0cHM6Ly9pZjIyMDEyOS5jbG91ZC5odGwtbGVvbmRpbmcuYWMuYXQiCiAgICAgIF0KICB9CiAgXSwKICAidXNlcnMiOiBbCiAgewogICAgInVzZXJuYW1lIjogImFkbWluIiwKICAgICJlbmFibGVkIjogdHJ1ZSwKICAgICJlbWFpbFZlcmlmaWVkIjogdHJ1ZSwKICAgICJjcmVkZW50aWFscyI6IFsKICAgICAgeyAidHlwZSI6ICJwYXNzd29yZCIsICJ2YWx1ZSI6ICJhZG1pbiIsICJ0ZW1wb3JhcnkiOiBmYWxzZSB9CiAgICBdLAogICAgInJlYWxtUm9sZXMiOiBbIkFkbWluIiwgIlVzZXIiXQogIH0KICBdCn0K
---

# ----------------------------------------
# Keycloak Deployment
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: student-if220129
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.1.1
          args:
            - start-dev
            - --import-realm
            - --http-port=8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: keycloak
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres-service:5432/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloak
            - name: KC_HOSTNAME_URL
              value: "https://if220129.cloud.htl-leonding.ac.at/keycloak"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/keycloak"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-realm
              mountPath: /opt/keycloak/data/import
              readOnly: true
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-realm
          secret:
            secretName: keycloak-realm-secret
        - name: keycloak-data
          emptyDir: {}
---
# ----------------------------------------
# Keycloak Service
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: student-if220129
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP


# ----------------------------------------
# Keycloak Service
# ----------------------------------------
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: student-if220129
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: "https"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "http"

spec:
  ingressClassName: nginx
  rules:
    - host: if220129.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /keycloak(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
